#!/usr/bin/env ruby

# vi: ft=ruby

VERSION = "0.1.0"
MINIMUM_RUBY_VERSION = "2.0.0"

CMD_HELP = "help"
CMD_VERSION = "version"
CMD_LIST_KEYS = "ls"
CMD_LIST_KEYS_LONG = "ls-l"
CMD_GET_VALUE = "get"
CMD_SHOW_STATS = "stats"
CMD_SHOW_ALL_STATS = "all-stats"

if Gem::Version.new(RUBY_VERSION) < Gem::Version.new(MINIMUM_RUBY_VERSION)
  STDERR.puts "memc requires Ruby #{MINIMUM_RUBY_VERSION} or later. You have #{RUBY_VERSION} installed."
end

require "socket"

class Main
  def self.help
    <<-EO_HELP
memc (v #{VERSION}) A memcached client for developers

* Friendly to humans (stats are summarised nicely)
* Friendly to piping its output to other unix tools (use grep/sed/awk
  etc. to filter/transform output)

Usage:

  memc SERVER_HOST:SERVER_PORT help        # this output
  memc SERVER_HOST:SERVER_PORT version     # show version
  memc SERVER_HOST:SERVER_PORT ls          # list all keys
  memc SERVER_HOST:SERVER_PORT ls-l        # list all keys and key sizes (bytes)
  memc SERVER_HOST:SERVER_PORT get KEYNAME # get the value associated with KEYNAME
  memc SERVER_HOST:SERVER_PORT stats       # show human readable stats
  memc SERVER_HOST:SERVER_PORT all-stats   # show raw stats from memcached

Examples:

  $ memc localhost:11211 stats
  $ memc localhost:11211 ls
  $ memc localhost:11211 ls | grep "interesting-thing"
  $ memc localhost:11211 get some-key-name

    EO_HELP
  end

  def self.main(argv: ARGV, stdout: STDOUT, stderr: STDERR)
    if argv.length == 1
      cmd = argv.shift

      case cmd
      when CMD_VERSION
        stdout.puts VERSION
      else
        stdout.puts help
      end

      return
    end

    server_host_and_port = argv.shift
    cmd = argv.shift || CMD_HELP
    client = MemcacheClient.new(server_host_and_port)

    case cmd
    when CMD_HELP
      stdout.puts help
    when CMD_VERSION
      stdout.puts VERSION
    when CMD_LIST_KEYS
      stdout.puts client.list_keys
    when CMD_LIST_KEYS_LONG
      stdout.puts client.list_keys_long
    when CMD_GET_VALUE
      key_name = argv.shift
      # use IO#print here instead of IO#puts because we want to ensure we
      # return only the value i.e. we don't want to add a trailing newline to
      # the value
      stdout.print client.get_value(key_name).join("\n")
    when CMD_SHOW_STATS
      stdout.puts client.get_most_interesting_stats
    when CMD_SHOW_ALL_STATS
      stdout.puts client.get_stats
    else
      stdout.puts <<-EO_MSG
Unrecognised command: #{cmd}

#{help}
      EO_MSG
    end

    client.close
  end
end

class TimeUtil
  SECS_IN_MIN = 60
  SECS_IN_HOUR = 60 * SECS_IN_MIN
  SECS_IN_DAY = 24 * SECS_IN_HOUR

  ##
  # Convert a number of seconds into a human readable time duration
  #
  # @param [Integer|String] num_seconds
  # @return [String] human readable description of duration
  #
  def self.humanize(num_seconds)
    total = Integer(num_seconds) # raises ArgumentError if it cannot convert
    fail ArgumentError if total <= 0 # zero or negative durations are not valid

    num_days = if total >= SECS_IN_DAY
                 total / SECS_IN_DAY
               else
                 0
               end

    without_days = total - (num_days * SECS_IN_DAY)

    num_hours = if without_days >= SECS_IN_HOUR
                 without_days / SECS_IN_HOUR
               else
                 0
               end

    without_days_and_hours = without_days - (num_hours * SECS_IN_HOUR)

    num_mins = if without_days_and_hours >= SECS_IN_MIN
                 without_days_and_hours / SECS_IN_MIN
               else
                 0
               end

    without_days_hours_mins = without_days_and_hours - (num_mins * SECS_IN_MIN)

    output = []
    output << "#{num_days} days" if num_days > 0
    output << "#{num_hours} hours" if num_hours > 0
    output << "#{num_mins} mins" if num_mins > 0
    output << "#{without_days_hours_mins} seconds" if without_days_hours_mins > 0

    output.join(", ")
  end
end

##
# https://github.com/memcached/memcached/blob/master/doc/protocol.txt
#
class MemcacheClient
  EOM = "END\r\n"

  def initialize(server_host_and_port)
    server_host, server_port = server_host_and_port.split(":")
    @socket = TCPSocket.open(server_host, Integer(server_port))
  end

  def get_value(key_name)
    lines = send_msg("get #{key_name}")

    # discard the first line because it just contains metadata
    lines.drop(1)
  end

  def get_stats
    send_msg("stats")
  end

  def get_most_interesting_stats
    stats = send_msg("stats").reduce(Hash.new) do |memo, s|
      k, v = s.split(" ")[1..2]
      memo[k] = v
      memo
    end

    formatters = Hash.new(->(raw) { raw })

    formatters["uptime"] = ->(num_secs) { TimeUtil.humanize(num_secs) }
    formatters["accepting_conns"] = ->(raw) { raw == "1" ? "Yes" : "No" }
    formatters["time"] = ->(raw) { Time.at(Integer(raw)).utc.to_s }
    formatters["limit_maxbytes"] = ->(raw) { "#{(Float(raw) / 1024 / 1024).round(2)} MB" }
    formatters["bytes"] = ->(raw) { "#{(Float(raw) / 1024 / 1024).round(4)} MB" }

    formatted_stats = stats.reduce({}) do |memo, (k, v)|
      memo[k] = formatters[k].call(v)
      memo
    end

    <<-EO_STATS
Memcached Server
  Version: #{formatted_stats["version"]}
  Uptime: #{formatted_stats["uptime"]}
  Current server time: #{formatted_stats["time"]}
  Currently accepting connections: #{formatted_stats["accepting_conns"]}
Connections
  Currently open connections: #{formatted_stats["curr_connections"]}
  Max num simultaneous connections: #{formatted_stats["max_connections"]}
Items
  Current stored items: #{formatted_stats["curr_items"]}
  Current mem used to store items: #{formatted_stats["bytes"]}
  Max mem server can use for storage: #{formatted_stats["limit_maxbytes"]}
  Num items removed from cache to free memory for new items: #{formatted_stats["evictions"]}
Errors
  Num connections closed by lack of memory: #{formatted_stats["read_buf_oom"]}
Usage (since last server reboot)
  Read requests:  #{formatted_stats["cmd_get"]}
  Store requests: #{formatted_stats["cmd_set"]}
  Flush requests: #{formatted_stats["cmd_flush"]}
  Touch Request:  #{formatted_stats["cmd_touch"]}
Detailed Usage (since last server reboot)
  GET:   hits: #{formatted_stats["get_hits"]}, misses: #{formatted_stats["get_misses"]}, expired: #{formatted_stats["get_expired"]}, flushed: #{formatted_stats["get_flushed"]}
  INCR:  hits: #{formatted_stats["incr_hits"]}, misses: #{formatted_stats["incr_misses"]}
  DECR:  hits: #{formatted_stats["decr_hits"]}, misses: #{formatted_stats["decr_misses"]}
  TOUCH: hits: #{formatted_stats["touch_hits"]}, misses: #{formatted_stats["touch_misses"]}
  CAS:   hits: #{formatted_stats["cas_hits"]}, misses: #{formatted_stats["cas_misses"]}, badval: #{formatted_stats["cas_badval"]}
    EO_STATS
  end

  def close
    @socket.close
  end

  def list_keys
    stats_items_result = parse_stats_items_msg(send_msg("stats items"))

    stats_items_result.map do |slab_num, num_items|
      results = parse_stats_cachedump_msg(send_msg("stats cachedump #{slab_num} 0"))
      results.keys
    end
  end

  def list_keys_long
    stats_items_result = parse_stats_items_msg(send_msg("stats items"))

    stats_items_result.map do |slab_num, num_items|
      results = parse_stats_cachedump_msg(send_msg("stats cachedump #{slab_num} 0"))
      results.map { |key_name, key_size| "#{key_name} #{key_size}" }
    end
  end

  private

  # {
  #   slab_id => num_items_in_slab,
  #   slab_id => num_items_in_slab,
  #   slab_id => num_items_in_slab,
  #   ...
  # }
  def parse_stats_items_msg(lines)
    re = /\ASTAT items:(\d+):number (\d+)\z/
    output = {}

    lines.grep(re).each do |line|
      matches = line.match(re)
      slab_id = matches[1]
      num_items = Integer(matches[2])

      output[slab_id] = num_items
    end

    output
  end

  # {
  #   "keyname" => 12335, # size of key in bytes
  #   "keyname" => 12335, # size of key in bytes
  # }
  def parse_stats_cachedump_msg(lines)
    re = /\AITEM (.+) \[(\d+) b; (\d+) s\]\z/
    lines.reduce({}) do |memo, line|
      matches = line.match(re)
      memo[matches[1]] = matches[2]
      memo
    end
  end

  # returns the response to the given command
  def send_msg(msg)
    @socket.print "#{msg}\r\n"

    lines = []

    while line = @socket.gets
      break if line == EOM
      lines << line.chop
    end

    lines
  end
end

# Only run `Main.main` if this script was the one invoked on the command line.
Main.main if __FILE__ == $PROGRAM_NAME