name: CI
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  specs:
    runs-on: ubuntu-latest
    services:
      db:
        image: memcached:latest
        ports: ['11211:11211']
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v2
      - name: Install Ruby (version given by .ruby-version) and Bundler
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run Ruby linting
        run: bundle exec rubocop
      - name: Run rspec
        run: bundle exec rspec
